version: "3.7"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_ROOT_HOST: "%"
    volumes:
      -  ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8383:8080"
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge